/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("java")
}

repositories {
    mavenCentral()  // Dépôt Maven Central pour les dépendances
}

dependencies {
    // Dépendances pour JUnit Jupiter (JUnit 5)
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.2")
    testImplementation("org.junit.jupiter:junit-jupiter-engine:5.8.2")

    // Dépendances pour le code de production (ajoutez celles dont vous avez besoin)
    implementation("org.apache.commons:commons-lang3:3.12.0")  // Exemple
}

tasks.test {
    useJUnitPlatform()  // Utilise JUnit 5 pour les tests
}