@startuml AST
    class AST extends Node {
        - File root
    }
    AST o--- File

    interface Node {
        + void vizualisation(BufferedWriter writer,  String nodeName) throws IOException
        + Node simplify()
    }

    class File implements Node { 
        - List<Def> defs 
        - List<Stmt> stmts 
        + File()
        + List<Def> getDefs()
        + void addDefs(Def def)
        + List<Stmt> getStmts()
        + void addStmt(Stmt stmt)
    }
    File o--- "*" Def
    File o--- "*" Stmt

    class Def implements Node {
        - Ident ident
        - List<Ident> idents
        - Stmt suite
        + Def() 
        + Ident getIdent()
        + void setIdent(Ident new_ident)
        + List<Ident> getIdents()
        + void addIdent(Ident new_idents)
        + Stmt getSuite()
        + void setSuite(Stmt suite)
    }
    Def o--- Ident
    Def o--- Stmt
    Def o--- "*" Ident

    class Suite implements Node {
        - List<Stmt> stmts
        + Suite()
        + List<Stmt> getStmts()
        + void addStmt(Stmt stmt)
    }
    Suite o--- "*" Stmt

    interface SimpleStmt extends Stmt

    class Return implements SimpleStmt {
        - Expr expr
        + Return()
        + Expr getExpr()
        + void setExpr(Expr expr)
    }
    Return o--- Expr

    class Print implements SimpleStmt {
        - Expr expr
        + Print()
        + Expr getExpr()
        + void setExpr(Expr expr)
    }
    Print o--- Expr

    class Affect implements SimpleStmt {
        - Expr leftExpr
        - Expr rightExpr
        + Affect()
        + Ident getIdent()
        + void setIdent(Ident ident)
        + Expr getExpr()
        + void setExpr(Expr expr)
    }
    Affect o--- "2" Expr

    interface Stmt extends Node

    class If implements Stmt {
        - Expr ifExpr
        - Suite then
        + If()
        + Expr getExpr()
        + void setExpr(Expr ifExpr)
        + Suite getThen()
        + void setThen(Suite then)
    }
    If o--- Expr
    If o--- Suite

    class IfElse implements Stmt {
        - Expr ifExpr
        - Suite then
        - Suite elseBlock
        + IfElse()
        + Expr getIf()
        + void setIf(Expr ifExpr)
        + Suite getThen()
        + void setThen(Suite then)
        + Suite getElse()
        + void setElse(Suite elseBlock)
    }
    IfElse o--- Expr
    IfElse o--- "2" Suite


    class For implements Stmt {
        - Ident ident
        - Expr expr
        - Suite suite
        + For()
        + Ident getIdent()
        + void setIdent(Ident ident)
        + Expr getExpr()
        + void setExpr(Expr expr)
        + Suite getSuite()
        + void setSuite(Suite suite)
    } 
    For o--- Expr
    For o--- Ident
    For o--- Suite

    interface Expr extends SimpleStmt 

    class OrExpr implements Expr{
        - List<AndExpr> exprs
        + OrExpr()
        + List<AndExpr> getOrExprs()
        + void addOrExpr(AndExpr expr)
    }
    OrExpr o--- "*" AndExpr

    class AndExpr extends OrExpr{
        - List<NotExpr> exprs
        + AndExpr()
        + List<NotExpr> getAndExprs()
        + void addAndExpr(NotExpr expr)
    }
    AndExpr o--- "*" NotExpr
    
    class NotExpr extends AndExpr {
        - NotExpr expr
        + NotExpr()
        + NotExpr getNotExpr()
        + void setNotExpr(NotExpr expr) 
    }
    NotExpr o--- NotExpr

    class CompExpr extends NotExpr {
        - CompBinop symbole
        - AddExpr left
        - AddExpr right
        + CompExpr()
        + CompBinop getCompSymbole()
        + void setCompSymbole(CompBinop symbole)
        + AddExpr getLeft()
        + void setLeft(AddExpr left)
        + AddExpr getRight()
        + void setRight(AddExpr right)
    }
    CompExpr o--- "2" AddExpr

    enum CompBinop {
        LESS_THAN
        LESS_EQUAL
        GREATER_THAN
        GREATER_EQUAL
        EQUAL
        NOT_EQUAL
    }

    CompBinop -- CompExpr

    interface LeftAssociativity {
        + void leftRotate()
    }

    class AddExpr extends CompExpr implements LeftAssociativity{
        - AddBinop symbole
        - AddExpr left
        - AddExpr right
        + AddExpr()
        + AddBinop getAddSymbole()
        + void setAddSymbole(AddBinop symbole)
        + AddExpr getLeft()
        + void setLeft(AddExpr left)
        + AddExpr getRight()
        + void setRight(AddExpr right)
    }
    AddExpr o--- "2" AddExpr

    enum AddBinop {
        ADD 
        SUB
    }

    AddBinop -- AddExpr

    class MutExpr extends AddExpr implements LeftAssociativity {
        - MutBinop symbole
        - MutExpr left
        - MutExpr right
        + MutExpr()
        + MutBinop getMutSymbole()
        + void setMutSymbole(MutBinop symbole)
        + MutExpr getLeft()
        + void setLeft(MutExpr left)
        + MutExpr getRight()
        + void setRight(MutExpr right)
    }
    MutExpr o--- "2" MutExpr

    enum MutBinop {
        MULT
        DIV
        MOD
    }
    MutExpr -- MutBinop

    class MinusExpr extends MutExpr  {
        - MinusExpr expr
        + MinusExpr()
        + MinusExpr getMinusExpr()
        + void setMinusExpr(MinusExpr expr) 
    }
    MinusExpr o--- MinusExpr

    abstract class TermExpr extends MinusExpr

    class IdentP extends TermExpr {
        - Ident ident
        - List<Expr> exprs
        + IdentP()
        + Ident getIdent() 
        + void setIdent(Ident ident)
        + List<Expr> getExprs()
        + void addExprs(Expr expr)
    }
    IdentP o--- Ident
    IdentP o--- "*" Expr

    class Ident extends TermExpr {
        - String name
        + Ident()
        + Ident(String name)
        + String getName()
        + void setName(String name)
    }

    class List extends TermExpr {
        - List<Expr> exprs
        + List()
        + List<Expr> getExprs()
        + void addExprs(Expr expr)
    }
    List o--- "*" Expr


    class Parenthese extends TermExpr {
        - Expr expr
        + Parenthese()
        + Expr getExpr()
        + void setExpr(Expr expr)
    }
    Parenthese o--- Expr
    
    abstract class Const extends TermExpr 
  
    class IntegerType extends Const {
        - int value
        + IntegerType()
        + IntegerType(int value)
        + int getValue()
        + void setValue(int value)
    }

    class StringType extends Const {
        - String value
        + StringType()
        + StringType(String value)
        + String getValue()
        + void setValue(int value)
    }

    class BoolType extends Const {
        - boolean value
        + BoolType()
        + BoolType(boolean value)
        + boolean getValue()
        + void setValue(boolean value)
    }

    class NoneType extends Const

@enduml